#ifndef FMODTAPESTOPPLUGIN_PARAMETERINDEX_H
#define FMODTAPESTOPPLUGIN_PARAMETERINDEX_H

/**
 * @brief パラメーターインデックス
 */
enum {
    TAPESTOP_PARAM_VOLUME = 0,
    NUM_PARAMETERS,
};

#endif //FMODTAPESTOPPLUGIN_PARAMETERINDEX_H
